### ISSUE TITLE
Add basic Layer Manager for the Viewer

### ISSUE THREAD

**Issue by zglueck** [NASAWorldWind/WorldWindServerKit#111]
This task is part of the #107 epic to implement a WorldWind Viewer into the WWSK.

The layer manager is the primary interface between the user and the data available from the WWSK while using the viewer. In this capacity, the following requirements are desired for the initial implementation:

- [x] Automatic WMS Layer Population from Server Contents
- [ ] ~Property Management~
- [ ] ~Style Management~
- [x] Property/Selection Persistence

**Comment by emxsys** [comment]
@zglueck @Beak-man, for the GeoServer viewer prototype, I added the [WorldWindExplorer](https://github.com/NASAWorldWindResearch/WorldWindExplorer) app to the geoserver/explorer endpoint (the endpoint is arbitrary); and I changed the layout to show the Layers tab at startup, hide the Output panel, and re-purpose the Home tab for settings.  The LayerManager is ready for modification.

**Comment by zglueck** [comment]
The WorldWind Explorer application layer manager was modified to include:
- persistence of select properties
- automatic WWSK wms and wfs layer loading or page load 
- basic layer ordering UI components

**Comment by emxsys** [comment]
The [WorldWindExplorer](https://github.com/NASAWorldWindResearch/WorldWindExplorer) was used as the prototype for the layer viewer. It's LayerManager was embellished with loading, persistence, sorting of the GeoServer's WMS and WFS layers.
