### ISSUE TITLE
Provide WorldWind viewer with URL parsing capabilities to serve as a layer previewer.

### ISSUE THREAD

**Issue by Beak-man** [NASAWorldWind/WorldWindServerKit#112]
As part of #107, the Web WorldWind-based viewer should have URL parsing capabilities. ~As a first stage, we can implement referencing a layer in the URL so the viewer can substitute the OpenLayers-based layer previewer in GeoServer, essentially widening the original scope of #90, and removing the need of building a layer previewed inside GeoServer's Apache Wicket/FreeMarker web views prerogatives.~ Generating and consuming URL parameters that include layers and the camera position provides the basis for creating and sharing "bookmarks" though email links and other media.

The idea is to make WebWW Explorer-based viewer to receive and parse the URL to retrieve a layer reference (for instance, using the current URL string format that WWSK has for the layer preview).

**Comment by emxsys** [comment]
Added the capability to generate a WWSK Explorer URL with the active layers and to restore the layers from the URL.  A "share" button was added to the nav-bar menu to generate a URL and copy it to the clipboard.
