### ISSUE TITLE
Adding a new JP2ECW data store causes GeoServer to crash

### ISSUE THREAD

**Issue by emxsys** [NASAWorldWind/WorldWindServerKit#13]
Adding a new .jp2 image using the _JP2ECW - JP2K (ECW) Coverage_ data source causes GeoServer to crash.  

The server is running on Linux Ubuntu16.04 LTS and configured with GDAL Ubuntu x64 natives and bindings from http://demo.geo-solutions.it/share/github/imageio-ext/releases/1.1.X/1.1.16/

The GeoServer log contains:
```	
terminate called after throwing an instance of 'std:length_error'
	  what(): basic_string::_S_create
```

**Comment by emxsys** [comment]
The GDAL ECW library has a "w_char" bug that is exercised when it looks for a user preferences file.  In lieu of recompiling the library with a patch (see: http://gis.stackexchange.com/questions/158828/geoserver-ecw-plugin-problem), we simply set the NCS_USER_PREFS environment variable prior to running GeoServer.  

Setting NCS_USER_PREFS to any value will cause the code to skip the offending branch. The _env.sh_ script sets the variable to the same value that the offending branch was attempting to do. (See: https://github.com/makinacorpus/libecw/blob/master/Source/C/NCSUtil/NCSPrefsXML.cpp.rej)

_env.sh snippet_
```
# -----------------------------------------------------------------------------
# HACK for JP2ECW crash.
#
# The GDAL ECW library has a "w_char" bug that can crash Geoserver with:
# > terminate called after throwing an instance of 'srd::length_error'
# >   what(): basic_string::S_create
# > Aborted (core dumped) 
# See http://gis.stackexchange.com/questions/158828/geoserver-ecw-plugin-problem
#
# Setting the NCS_USER_PREFS environment variable to any value will cause the 
# code to skip the offending branch. This hack sets the variable to the same
# value that the offending branch was attempting to do. See this patch:
# https://github.com/makinacorpus/libecw/blob/master/Source/C/NCSUtil/NCSPrefsXML.cpp.rej
# -----------------------------------------------------------------------------
if [ -z "${NCS_USER_PREFS}" ]; then
    if [ -z "${HOME}" ]; then
        export NCS_USER_PREFS=${HOME}/.erm/ncsuserprefs.xml
    else
        export NCS_USER_PREFS=/etc/erm/ncsuserprefs.xml
    fi
fi
```

**Comment by 1Map** [comment]
Ok, done as above, but now it crashes on VRTFormat.

Before applying above it crashed on:

```
15 Apr 11:04:55 DEBUG [gdal.jp2mrsid] - Creating a new JP2KFormat.
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_S_create

```
Now it crashes on:

```
15 Apr 11:15:01 DEBUG [gdal.vrt] - Creating a new VRTFormat.
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_S_create

```

**Comment by emxsys** [comment]
@1Map,
What version of WWSK/GeoServer did this occur on?  
Can you provide an example of the VRT data source?
