### ISSUE TITLE
Update Web WorldWind library

### ISSUE THREAD

**Issue by Beak-man** [NASAWorldWind/WorldWindServerKit#139]
Update WWSK's Explorer Web WorldWind library to 0.9.0.

**Comment by emxsys** [comment]
The WebWorldWind 0.9.0 library updates were inadvertently applied to a viewer prototype module and not to the `worldwind-gs-explorer` module as intended.

**Comment by emxsys** [comment]
Updated the WebWorldWind js dependencies in the `worldwind-gs-explorer` module to v0.9.0 in the [WWSK v0.5.1 Hotfix](https://github.com/NASAWorldWind/WorldWindServerKit/milestone/10)

See commit: ca2bb6399
