### ISSUE TITLE
Publish SRTM30 Elevation and BMNG2004 data?

### ISSUE THREAD

**Issue by AreaOfLongRong** [NASAWorldWind/WorldWindServerKit#20]
I'm using WorldWind Java SDK for my application develop. How can I publish SRTM30 Elevation and BMNG2004 data with WoldWindServerKit?

**Comment by emxsys** [comment]
@AreaOfLongRong, we're currently looking into publishing the .bil and .dds elevation formats used by the WWJ clients.  You can follow the progress in issue #40.
