### ISSUE TITLE
Document observations for WWSK 

### ISSUE THREAD

**Issue by eirizarry** [NASAWorldWind/WorldWindServerKit#51]
- [x] Run all examples for WWSK

- [x] Document all impressions and any issues found

**Comment by eirizarry** [comment]
Got the server up and running on Friday (6/30), but didn't realize that I set it up from the 'develop' branch. As a result, the GeoServer web admin interface did not load fully. 

Tried today to setup GeoServer using 'master', but it did not work. I used the "Deploy a binary distribution" option. Everything went well until I pointed my browser to http://localhost:8080/geoserver/index.html at which it said that the service was unavailable.

**Comment by pdavidc** [comment]
Thanks, Endia. Would you please chat with @emxsys this week to determine what might have gone wrong?

**Comment by eirizarry** [comment]
@pdavidc Sure thing, I will set it up.

**Comment by emxsys** [comment]
@eirizarry I reported your discovery in issue #62 (including a workaround).

**Comment by eirizarry** [comment]
Thank you for looking into this, Bruce! I will try again, this time using the workaround you included in [#62](https://github.com/NASAWorldWind/WorldWindServerKit/issues/62).

**Comment by eirizarry** [comment]
For running the server from the terminal, @emxsys 's workaround works great!
