### ISSUE TITLE
Cannot add a layer from a GeoPackage containing a hyphen in the table name

### ISSUE THREAD

**Issue by emxsys** [NASAWorldWind/WorldWindServerKit#72]
An exception is thrown when adding a layer from a GeoPackage data store when the contents table contains a hyphen "-"

_Error displayed in the GeoServer web admin interface_:
### Oops, something went wrong...
```
org.apache.wicket.WicketRuntimeException: Method onRequest of interface org.apache.wicket.behavior.IBehaviorListener targeted at org.apache.wicket.ajax.markup.html.AjaxLink$1@47187123 on component [AjaxLink [Component id = link]] threw an exception
.
.
.
Caused by: java.lang.reflect.InvocationTargetException at 
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at 
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at 
java.lang.reflect.Method.invoke(Method.java:498) at 
org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:258) ... 113 more 

Caused by: java.lang.RuntimeException: Error occurred while building the resources for the configuration page at org.geoserver.web.data.layer.NewLayerPage.buildLayerInfo(NewLayerPage.java:366) at 
org.geoserver.web.data.layer.NewLayerPage$8.onClick(NewLayerPage.java:280) at 
org.geoserver.web.wicket.SimpleAjaxLink$1.onClick(SimpleAjaxLink.java:47) at 
org.apache.wicket.ajax.markup.html.AjaxLink$1.onEvent(AjaxLink.java:85) at 
org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:155) at 
org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:601) ... 118 more 

Caused by: java.io.IOException: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "-": syntax error) at gov.nasa.worldwind.geopkg.GeoPackage.getTileBound(GeoPackage.java:1430) at
gov.nasa.worldwind.geopkg.mosaic.GeoPackageReader.read(GeoPackageReader.java:272) at 
org.geoserver.catalog.CoverageDimensionCustomizerReader.read(CoverageDimensionCustomizerReader.java:232) at 
org.geoserver.catalog.SingleGridCoverage2DReader.read(SingleGridCoverage2DReader.java:145) at 
org.geoserver.catalog.CatalogBuilder.buildCoverageInternal(CatalogBuilder.java:1006) at 
org.geoserver.catalog.CatalogBuilder.buildCoverage(CatalogBuilder.java:899) at 
org.geoserver.catalog.CatalogBuilder.buildCoverage(CatalogBuilder.java:859) at 
org.geoserver.web.data.layer.NewLayerPage.buildLayerInfo(NewLayerPage.java:356) ... 123 more 

Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "-": syntax error) at org.sqlite.core.DB.newSQLException(DB.java:909) at 
org.sqlite.core.DB.newSQLException(DB.java:921) at org.sqlite.core.DB.throwex(DB.java:886) at 
org.sqlite.core.NativeDB.prepare_utf8(Native Method) at 
org.sqlite.core.NativeDB.prepare(NativeDB.java:127) at org.sqlite.core.DB.prepare(DB.java:227) at 
org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:81) at 
org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208) at 
org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208) at 
gov.nasa.worldwind.geopkg.GeoPackage.getTileBound(GeoPackage.java:1413) ... 130 more 

```

**Comment by emxsys** [comment]
My preliminary investigation reveals that wrapping the table name with brackets ("[" and "]") resolves the issue. Finding the official documentation on this technique has been elusive.  However, the [SQLLite Keywords](https://www.sqlite.org/lang_keywords.html) documentation does touch on the matter of quoting keywords.

A comprehensive treatment of the GeoPackage code must be applied to ensure both reading and writing GeoPackage tables is addressed.

**Comment by pdavidc** [comment]
@emxsys Have you tried loading one of these problematic GeoPackges into WorldWind Android? Two questions come to mind:
- Do the SQLite libraries used by GeoServer and Android differ in this regard?
- Do we need to fix this issue in both ServerKit and Android?

**Comment by zglueck** [comment]
Further investigation indicates this issue isn't limited to hyphens. Any GeoPackage with a `table_name` that must be quoted in SQLite will fail with the current SQL statement handling. @emxsys link to the SQLite keywords is one starting point for words which conflict and how to account with quotes.

I've added a few unit tests to demonstrate the issue and a proposed solution for the GeoServer GeoPackage module. The fix involved adding single quotes around most uses of the `table_name`. When the variable is used as a parameter in a PreparedStatement quotes are not needed.

@pdavidc yes, this is something the WWA implementation needs to track as well. Providing one of the problematic GeoPackages to WWA currently works, because the query instance with `table_name` already has quotes. Any future work with GeoPackage and the user data table will require similar treatment.
