### ISSUE TITLE
GeoPackages exported from Layer Preview do not have same fidelity as source imagery

### ISSUE THREAD

**Issue by emxsys** [NASAWorldWind/WorldWindServerKit#75]
GeoPackages exported from the Layer Preview have a lower resolution than the source imagery. It appears the number of levels for the GeoPackage, as determined by GeoServer, is too low to represent the source imagery accurately.

### Source Imagery
![image](https://user-images.githubusercontent.com/191515/28547632-a545c7e2-7084-11e7-9e16-d225ff3dfa7b.png)
_Figure 1. Source GeoTIFF_
The image in figure 1 is the source GeoTiff image at full resolution in QGIS.

### Exported GeoPackage
![image](https://user-images.githubusercontent.com/191515/28547656-c0b68cbe-7084-11e7-8187-f9f98ecdf55c.png)
_Figure 2._GeoPackage exported by Layer Preview_
The image in figure 2 is the GeoPackage created from the source imagery by the Layer Preview. It contains levels 11-15. It displayed in QGIS at the same resolution as figure 1.

### Comparative GeoPackage
![image](https://user-images.githubusercontent.com/191515/28547877-d950e282-7085-11e7-85bb-27075c8c1ce2.png)
_Figure 3. GeoPackage exported with WPS_ 
The image in figure 3 is GeoPackage created from the source imagery via WPS.   It contains levels 11-17.  It displayed in QGIS at the same resolution as figure 1.

**Comment by emxsys** [comment]
This issue is related to issue #17.  The min/max zoom levels determined in test case are 11-16 [as determined by `AbstractTilesGetMapOutputFormat.addTiles(TilesFile tiles, List<MapLayerInfo> mapLayers, GetMapRequest request, String name)`] yet only levels 11-15 are in the resulting GeoPackage.

**Comment by emxsys** [comment]
### Observations

- `GeoPackageGetMapOutputFormat `inherits from `AbstractTilesGetMapOutputFormat`
- `AbstractTilesGetMapOutputFormat.findMinMaxZoom` uses `findClosestZoom `for min zoom `findMaxZoomAuto `for the max zoom
- `AbstractTilesGetMapOutputFormat.findClosestZoom` returns a zoom level where the scale is close to the scale required for the map extents at a single tile's width (256 px)
- `AbstractTilesGetMapOutputFormat.findMaxZoomAuto` returns a "zoom level + 1" where the number of tiles in the selected zoom level is greater than 256

**Comment by emxsys** [comment]
### Issue
The criteria for the maximum zoom level used in a GeoPackage created from the Layer Preview UI is that the level contains at least 256 tiles.  This maximum level's scale may be less than the scale of the source imagery, resulting the in loss of fidelity in the exported GeoPackage.
### Workaround
The following XML can be pasted into GeoServer's WPS Request Builder for the gs:GeoPackage process and edited to generate a GeoPackage with the desired zoom levels.
```
    <geopackage xmlns="http://www.opengis.net/gpkg"  name="filename">
        <tiles identifier="table_id" name="table_name">
            <description>Table description</description>
            <srs>EPSG:4326</srs>
            <bbox>
                <minx></minx>
                <miny></miny>
                <maxx></maxx>
                <maxy></maxy>
            </bbox>        
            <format>image/vnd.jpeg-png</format>
            <coverage>
                <minZoom></minZoom>
                <maxZoom></maxZoom>
            </coverage>
            <layers>layer_name(s)</layers>
            <styles>raster</styles>
        </tiles>
    </geopackage>
```
- Set the `<geopackage/>` name attribute to the exported filename (sans extension
- Set the `<tiles/>` identifier and name attributes to unique values
- Set the `<description/>` text to something meaningful
- Set the `<bbox/>` values
- Set the `<minZoom/>` value
- Set the `<maxZoom/>` value. _Note the maxZoom value is not inclusive; it must be +1 value greater than the desired maximum zoom level in the exported GeoPackage._
- Set the `<layers/>` text to a comma delimited list of the layers used to generate the map tiles. 

See GeoServer's [GeoPackage as Output: GeoPackage WPS Process](http://docs.geoserver.org/latest/en/user/community/geopkg/output.html#geopackage-wps-process) and the [WPS Request Builder](http://docs.geoserver.org/latest/en/user/services/wps/requestbuilder.html) documentation for more information.

**Example:**
![image](https://user-images.githubusercontent.com/191515/28631825-6d07787a-71e3-11e7-9770-6c329e0513cc.png)

Upon completion, a link to the exported GeoPackage will displayed in place of the "Loading..." text in the popup window. Copy this link and open it in another tab/window to download the GeoPackage.  Note: this link will expire, so a timely download is required to avoid having to resubmit the WPS request.

**Comment by emxsys** [comment]
### Proposed Solution
Determine the scale of the highest resolution coverage in the WMS GetMap application/x-gpkg request and then use the level in the GeoPackage grid set that is closest to that scale.  If there is a failure (e.g., no coverage data), then fall back onto the existing "greater than 256 tiles" criteria.

**Comment by emxsys** [comment]
### Solution
Compute the maximum zoom level by interrogating the layer(s) to get the highest resolution coverage's scale and then find closest zoom level for that scale.

**Comment by PJHogan** [comment]
Seems simple enough strung together now. But that's one hell of a sequence!!!
